/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.ColaL;
import Negocio.Practica;
import Negocio.PilaLista;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PilaCOla extends javax.swing.JFrame {

    PilaLista PLista;
    ColaL CLista;

    /**
     * Creates new form PilaCOla
     */
    public PilaCOla() {
        PLista = new PilaLista();
        CLista = new ColaL();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PushLista = new javax.swing.JButton();
        ElementoLista = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaLista = new javax.swing.JTextArea();
        PopLista = new javax.swing.JButton();
        GetLista = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        EncolarLista = new javax.swing.JButton();
        ElementoLista1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        AreaLista1 = new javax.swing.JTextArea();
        DecolarLista = new javax.swing.JButton();
        GetLista1 = new javax.swing.JButton();
        Invertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Elemento:");

        PushLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PushLista.setText("Push");
        PushLista.setEnabled(false);
        PushLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushListaActionPerformed(evt);
            }
        });

        ElementoLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ElementoLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ElementoListaKeyReleased(evt);
            }
        });

        AreaLista.setEditable(false);
        AreaLista.setColumns(20);
        AreaLista.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AreaLista.setRows(5);
        jScrollPane3.setViewportView(AreaLista);

        PopLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PopLista.setText("Pop");
        PopLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopListaActionPerformed(evt);
            }
        });

        GetLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GetLista.setText("Get");
        GetLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(ElementoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PushLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GetLista)
                            .addComponent(PopLista))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PushLista)
                    .addComponent(ElementoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Cola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Elemento:");

        EncolarLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EncolarLista.setText("Encolar");
        EncolarLista.setEnabled(false);
        EncolarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncolarListaActionPerformed(evt);
            }
        });

        ElementoLista1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ElementoLista1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ElementoLista1KeyReleased(evt);
            }
        });

        AreaLista1.setEditable(false);
        AreaLista1.setColumns(20);
        AreaLista1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AreaLista1.setRows(5);
        jScrollPane4.setViewportView(AreaLista1);

        DecolarLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DecolarLista.setText("Decolar");
        DecolarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecolarListaActionPerformed(evt);
            }
        });

        GetLista1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GetLista1.setText("Get");
        GetLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetLista1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(ElementoLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(EncolarLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(GetLista1))
                    .addComponent(DecolarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EncolarLista)
                    .addComponent(ElementoLista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetLista1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DecolarLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Invertir.setText("Invertir");
        Invertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(Invertir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Invertir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PushListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushListaActionPerformed

        int x = Integer.valueOf(ElementoLista.getText());
        PLista.Push(x);
        AreaLista.setText(PLista.toString());
        ElementoLista.setText("");
        PushLista.setEnabled(false);
    }//GEN-LAST:event_PushListaActionPerformed

    private void ElementoListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElementoListaKeyReleased
        ValidarPush(ElementoLista.getText(), PushLista, ElementoLista);
    }//GEN-LAST:event_ElementoListaKeyReleased

    private void PopListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopListaActionPerformed
        if (!PLista.Vacia()) {
            int x = PLista.Pop();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x, "Pop", 1);
            AreaLista.setText(PLista.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos", "Estructura de Datos 1", 1);
        }
    }//GEN-LAST:event_PopListaActionPerformed

    private void GetListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetListaActionPerformed
        if (!PLista.Vacia()) {
            int x = PLista.Get();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x, "Get", 1);
            AreaLista.setText(PLista.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos", "Estructura de Datos 1", 1);
        }
    }//GEN-LAST:event_GetListaActionPerformed
    private void ValidarPush(String Valor, JButton Tamaño, JTextField Texto) {
        //JOptionPane.showMessageDialog(rootPane, );
        if (Valor.length() != 0) {
            //&& Integer.valueOf(Valor) > 0) {

            Tamaño.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(rootPane, "Elemento Invalido", "Estructura de Datos 1",1);
            Tamaño.setEnabled(false);
            //Texto.setText("");
        }

    }
    private void EncolarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncolarListaActionPerformed

        int x = Integer.valueOf(ElementoLista1.getText());
        CLista.Encolar(x);
        AreaLista1.setText(CLista.toString());
        ElementoLista1.setText("");
        EncolarLista.setEnabled(false);
    }//GEN-LAST:event_EncolarListaActionPerformed

    private void ElementoLista1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElementoLista1KeyReleased
        ValidarPush(ElementoLista1.getText(), EncolarLista, ElementoLista);
    }//GEN-LAST:event_ElementoLista1KeyReleased

    private void DecolarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecolarListaActionPerformed
        if (!CLista.Vacia()) {
            int x = CLista.Decolar();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x, "Decolar", 1);

            //  if (!PLista.Vacia()) {
            AreaLista1.setText(CLista.toString());
            /* } else {
                AreaLista.setText("Q-> [  ] ");
            }*/
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Cola no tiene Elementos", "Estructura de Datos 1", 1);
        }
    }//GEN-LAST:event_DecolarListaActionPerformed

    private void GetLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetLista1ActionPerformed
        if (!CLista.Vacia()) {
            int x = CLista.Get();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x, "Get", 1);
            AreaLista1.setText(CLista.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Cola no tiene Elementos", "Estructura de Datos 1", 1);
        }
    }//GEN-LAST:event_GetLista1ActionPerformed

    private void InvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvertirActionPerformed
        //if (CLista.getCant() == PLista.getCant()) {
            if (!CLista.Vacia() && !PLista.Vacia()) {
                Practica obj = new Practica(PLista, CLista);
                //obj.invertir2();
                CLista = obj.getCola();
                PLista = obj.getPila();
                AreaLista.setText(PLista.toString());
                AreaLista1.setText(CLista.toString());
            }
       /* }
        else{
            JOptionPane.showMessageDialog(rootPane, "La Pila y Cola no tienen la misma cantidad de datos", "Estructura de Datos 1", 1);
        }*/
    }//GEN-LAST:event_InvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilaCOla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilaCOla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilaCOla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilaCOla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilaCOla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaLista;
    private javax.swing.JTextArea AreaLista1;
    private javax.swing.JButton DecolarLista;
    private javax.swing.JTextField ElementoLista;
    private javax.swing.JTextField ElementoLista1;
    private javax.swing.JButton EncolarLista;
    private javax.swing.JButton GetLista;
    private javax.swing.JButton GetLista1;
    private javax.swing.JButton Invertir;
    private javax.swing.JButton PopLista;
    private javax.swing.JButton PushLista;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
